language: go
go:
  - master

services:
  - docker

install:
  - go get ./api/vendor/database
  - go get ./api

script:
  - cd ./api
  - go test

after_success:
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
  - docker build ./api -t mcmenemy/godorp_api:latest
  - docker push mcmenemy/godorp_api:latest
  - docker build ./frontend -t mcmenemy/godorp_frontend:latest
  - docker push mcmenemy/godorp_frontend:latest
  - docker build ./db -t mcmenemy/godorp_db:latest
  - docker push mcmenemy/godorp_db:latest

env:
  global:
    DOCKER_EMAIL:
      secure: K//bLlIJQS35oezeHMw9zFYUUZXrjisUE349wb8F3glEcerQBJfXAz6VVwoXuYBJtAWpkuf4AyBJCDUGKbo2OV/Z+ee5/BhICCDnHevKhTslrpJLKUHBwGt9h6NpdQwEbAFpnAyZFuSlyAzfIy9gkXmgwHfbrTrV1PdsOuerzi2rv/LQWOZwR/iFbVxPn7cDbrTzK/F8dC6uBsRYI4ddtf9N8o/UNa/nPdziVL3zgFI/ITsXf1E5J5g8Gjz5LVZ6rvUd3HS9aDxQJ8YhP/yiRv+5Ro3lbZCyu9Y6R/hqDTxXjgbC9zIHA0bR2g8Pg9MzLrl31m+8zPzSCBsBT0dsUcz4E947WukgsoCVvApMtL6EngpresH8RVnRamGNkPukmpm4bfsZ0ryNQ9BG4vGF+BnCJJeQZADoD916uN9fmqRDGBgzxQvkHID0kXNgpr9UXY8Tesz1/2KMQFEoxtGt1qQFA2vw5EyfeHEshn49uwaIa36D81+Cwr2BKeap/0QdopMDZbw67YZfAeKh8/2M2REmoM8lAF4o1qGkvSF+DuSFMmh3KhQwkdy94uFD1ffi65VJtSdLTCByap6pA0QfoBaIf+x/jKsQbPDu4G2F0u3WmhofTfLymuWYe9jo6tltJAs70dFdUN2suuUuM/eIfs2UluHBj/1B0pdQ6BwaDrQ=
    DOCKER_USER:
      secure: d+CeyOcvJv4cI7CnTb/vyl2chdz23PF9h/lzVI+cpyVQ1Wooy1XkCs+lyZJ48t4C0g5nOFH+WzjjbAKG6HzKUI+X9yHFQGLDhbb9rQ8/h1q0mbXZ7eDWNRDaPzGNDW2QBg49HolrmL+Tp1Ey/ei//R95tH4oebBioTZWMfLH4Y2BohbpFqR9iI3dfwQ4sHz25PN0J+36dl9q7QSq2ms0byg7dsosn04UWav2uCHBNYThU7MBjcXLFQS9R0oxpWDb3VQYDwtCl1z36+JEJtJpr/apb9rayR63ngHdUbQj6cZKT1Pn5IfTAHB+0Fbj5LsI/bUKAxNydjYpY7t4DzcYLopeyTd9aELl3CnftULuTY3Nm8zqn/jMaU5cEnUw/RYLjp5eJKvpxzplQcnXcABg8N6WIhtgBv+Ar948dbeVjkj4A0VlpLcC8bN0Hg71y96ytxGa6o/vfSTzfyPu8yX/EmvJsW/cisnKlyhT0v/SEauHi7lJWEVGvl0A6KEP6fpeQqtAV1VEphjMlRnE6RP3uhv4mB99NuOMAdCBOGTfBztcQ40Cux7/77ZLglI9mAKXx+oP+0HCBwW80B26AvVcdSmJb7d2t62+xZyeK511C/0vTQPN5U960cT3mm1S4PnQn7wzOUy+9lHxQGvloKJR8KDdznmqw7KqboQcnu1NZdU=
    DOCKER_PASS:
      secure: auF4f4vLFCz+azcEz6uUi8rsru14SwDdRQZQ4mVhzFAXRFRjd4e5ZbgBSWL/d99it/kOr83Dtw0IWZrr3ZgdzNSfyupep6uEyrn7VQBmPck5paicvR1VJe/7EwqDSr826GnmLWcqxZffmubsraHQMe2TqBL80iu65kYfN+TCyM3gzgvNGX/quvQ5NArj01lir6WuvYC4l/jcHX3Dc7kKo3gyJNroyA+ADRIrtdcNm7bQZigoEI6VFk9u0awu4wNFtI1W22hjUTkIInpIKQQrgBSOhn90a9Ii59ln3YpKEdO3SdFgtvFKH8qdc2elR/eUPSnLQSmtRw9VHpxoJzmCU1uzA2BoWASZ/nnaBZf/nSakB8EMZtso25KFg2LyNARu2a8Oi9k7UjanKhkvwJ3nyFFRkLPqDZzpKaJsuZWOpFz/PWcUqWXXeRmorOB14Q1ADN3ns/iMR5VAjiEVVhmjPDmLmLO2u2Lk0lKH3zWHm378rZ8TBH7Toh29L808YwYXLxwG2COK7ejyOqZyo0AFLmMIQW8Yw6D/e4noJTwU3S1dM2L+nRtq8RNhmiT2dR3O37l9znYyEifOXXaTovVGg3MtVg4gMsG341/xgmywIfk2IJTqPHJI5nzdSPl6CZKZJ+KVs3gj+GDg7Hg5NADeoDa5KjS+faWUU4qgZQVuBzg=
